name: repartapp
description: Aplicación para repartir gastos grupales.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    provider: ^5.0.0
    font_awesome_flutter: ^9.0.0
    google_sign_in: ^5.0.1
    firebase_auth: ^1.0.1
    firebase_core: ^1.0.2
    firebase_database: ^6.1.1
    google_fonts: ^2.0.0
    shared_preferences: ^2.0.5
    flutter_speed_dial: ^3.0.5
    firebase_dynamic_links: ^0.8.0
    share: ^2.0.1
    hive: ^2.0.2
    hive_flutter: ^1.0.0
    path_provider: ^2.0.1
    get: ^4.1.3
    get_it: ^6.0.0
    
dev_dependencies:
    flutter_test:
        sdk: flutter
    hive_generator: ^1.0.1
    build_runner: ^1.12.2

flutter:
    uses-material-design: true

    assets:
        - assets/
