name: splitex
description: Aplicación para repartir gastos grupales.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.11.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.2
    google_sign_in: ^5.0.3
    firebase_auth: ^1.2.0
    firebase_core: ^1.2.0
    firebase_database: ^6.1.2
    google_fonts: ^2.0.0
    shared_preferences: ^2.0.5
    flutter_speed_dial: ^3.0.5
    firebase_dynamic_links: ^2.0.2
    share: ^2.0.1
    hive: ^2.0.4
    hive_flutter: ^1.0.0
    path_provider: ^2.0.1
    get: ^4.1.3
    connectivity: ^3.0.3
    flutter_bloc: ^7.0.0
    linter: ^1.4.0
    intl: ^0.17.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    hive_generator: ^1.0.1
    build_runner: ^2.0.1

flutter:
    uses-material-design: true

    assets:
        - assets/
