name: repartapp
description: Aplicación para repartir gastos grupales.

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=2.7.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    provider: ^5.0.0
    font_awesome_flutter: ^9.0.0-nullsafety
    google_sign_in: ^5.0.0
    firebase_auth: ^1.0.1
    firebase_core: ^1.0.1
    firebase_database: ^6.1.0
    google_fonts: ^2.0.0
    shared_preferences: ^2.0.4
    flutter_speed_dial: ^3.0.5
    firebase_dynamic_links: ^0.8.0
    share: ^2.0.1

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    assets:
        - assets/
